version: '{build}'
image: Visual Studio 2022
environment:
  matrix:
    - SERVER_MODE: true
    - SERVER_PRO2_SUPPORT: true

install:
  - git submodule update --init --recursive

  # environment and system dependency
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/premake/premake-core/releases/download/v5.0.0-beta6/premake-5.0.0-beta6-windows.zip ; exit 0"
  - 7z x premake-5.0.0-beta6-windows.zip
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://github.com/libevent/libevent/releases/download/release-2.1.12-stable/libevent-2.1.12-stable.tar.gz ; exit 0"
  - tar xf libevent-2.1.12-stable.tar.gz
  - move libevent-2.1.12-stable event
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://www.lua.org/ftp/lua-5.4.7.tar.gz ; exit 0"
  - tar xf lua-5.4.7.tar.gz
  - move lua-5.4.7 lua
  
  - bash -c "curl --retry 5 --connect-timeout 30 --location --remote-header-name --remote-name https://www.sqlite.org/2025/sqlite-amalgamation-3490100.zip  ; exit 0"
  - 7z x sqlite-amalgamation-3490100.zip
  - move sqlite-amalgamation-3490100 sqlite3

  - git clone --depth=1 https://github.com/mercury233/irrlicht

before_build:
  - xcopy /E premake\* .
  - xcopy /E resource\* .
  - premake5 vs2022
  
configuration: Release
platform: x64

build: 
  project: build/YGOPro.sln
  parallel: true

test: off

for:
-
  matrix:
    only:
      - SERVER_PRO2_SUPPORT: true

  before_build:
    - xcopy /E premake\* .
    - xcopy /E resource\* .

    - premake5 vs2022

  after_build:
    - ps: move bin\release\x64\AI.Server.exe .

  artifacts:
    - path: AI.Server.exe
      name: YGOPro server for YGOPro2 AI

cache:
  - premake-5.0.0-beta6-windows.zip
  - libevent-2.1.12-stable.tar.gz
  - lua-5.4.7.tar.gz
  - sqlite-amalgamation-3490100.zip
